export const CONFIG = {
  sim: { seed: 0xf1a7, snapMax: 8192, coreFloor: 48 },
  worker: { TICK_MS: 5, MAX_CATCHUP_MS: 20, hzEmaTau: 0.5 },
  loop: { MAX_FRAME_DT: 0.05 },
  physics: {
    MASS: 1,
    INERTIA: 0.05,
    GRAVITY: 9.81,
    LIN_DRAG: 1.4,
    ANG_DRAG: 6.0,
    HOVER_S: 0,
    LIFT_K: 6,
    CRUISE_THRUST: 1.6,
    ROLL_K: 2.2,
    YAW_A_K: 1.4,
    THRUST_K: 4,
    YAW_K: 3,
    ESCAPE_TH: 0.5,
    ESCAPE_HYST: 0.15,
    ESCAPE_IMPULSE: 9,
    ESCAPE_LOCKOUT_S: 0.35,
    BOUNDS_K: 40,
    BOUNDS_C: 6,
    BOUNCE: 0.35,
    FLY_R: 0.25,
    CONTACT_STARTLE: 3,
    NOISE_AMP: 0.04,
    NOISE_HZ: 1.3,
  },
  sensing: {
    PROX_MAX: 20,
    EPS: 0.05,
    LOOM_CONE_DEG: 50,
    TAU_PROX: 0.08,
    TAU_LOOM: 0.06,
  },
  camera: { OFFSET: { x: -3.2, y: 1.4, z: 0 }, LOOKAHEAD: 2.5, omega: 14 },
  aesthetic: {
    BASE_SIZE: 1.5,
    CORE_SIZE: 3.0,
    ACT_SWELL: 1.6,
    POINT_SCALE: 90,
    POINT_MAX: 14,
    // Depth shading: points past NEAR fade toward the background, reaching
    // FADE (0..1) of the way there by FAR — gives the cloud volume instead of a
    // flat stipple. Tuned to the brainScale-10 placement.
    POINT_DEPTH_NEAR: 8,
    POINT_DEPTH_FAR: 42,
    POINT_DEPTH_FADE: 0.45,
    FLAP_MIN: 8,
    FLAP_MAX: 34,
    FLAP_AMP: 0.9,
    grid: true,
    grain: false,
    // Brain point cloud lives as one big fixed object in the world. The centre
    // sits on the fly's cruise line between its start (0,4,0) and the escape
    // block (9,4,0), so the fly flies through the connectome.
    brainScale: 10,
    brainCenter: { x: 6, y: 5, z: 0 },
  },
} as const;
