export const CONFIG = {
  sim: { seed: 0xf1a7, snapMax: 8192, coreFloor: 48 },
  worker: { TICK_MS: 5, MAX_CATCHUP_MS: 20, hzEmaTau: 0.5 },
  loop: { MAX_FRAME_DT: 0.05 },
  physics: {
    MASS: 1,
    INERTIA: 0.05,
    GRAVITY: 9.81,
    LIN_DRAG: 1.4,
    ANG_DRAG: 6.0,
    HOVER_S: 0,
    LIFT_K: 6,
    CRUISE_THRUST: 1.6,
    ROLL_K: 2.2,
    YAW_A_K: 1.4,
    THRUST_K: 4,
    YAW_K: 3,
    ESCAPE_TH: 0.5,
    ESCAPE_HYST: 0.15,
    ESCAPE_IMPULSE: 9,
    ESCAPE_LOCKOUT_S: 0.35,
    BOUNDS_K: 40,
    BOUNDS_C: 6,
    BOUNCE: 0.35,
    FLY_R: 0.25,
    CONTACT_STARTLE: 3,
    NOISE_AMP: 0.04,
    NOISE_HZ: 1.3,
    YAW_JITTER_DT: 0.05,
  },
  sensing: {
    PROX_MAX: 20,
    EPS: 0.05,
    EPS2: 0.05 * 0.05,
    LOOM_CONE_DEG: 50,
    TAU_PROX: 0.08,
    TAU_LOOM: 0.06,
    LIGHT_MAX: 4,
    TAU_LIGHT: 0.12,
    EYE_SPLAY: 0.6,
    WIND: { x: 1, y: 0, z: 0.35 },
    WIND_SPEED: 0.5,
    WIND_TURN_HZ: 0.03,
    TAU_WIND: 0.2,
  },
  lif: {
    defaults: { dtMs: 5, tauMMs: 20, vThreshold: 1, vReset: 0, refracMs: 2, noiseSigma: 0.02 },
    ranges: {
      dtMs: [1, 10],
      tauMMs: [2, 80],
      vThreshold: [0.3, 3],
      vReset: [-1, 0.5],
      refracMs: [0, 10],
      noiseSigma: [0, 0.3],
    },
  },
  audio: {
    ambientFreqs: [55, 82.5, 110],
    lowpassHz: 380,
    lfoHz: 0.05,
    WING_HZ_MIN: 120,
    WING_HZ_MAX: 900,
    WING_GAIN_MAX: 0.15,
    blip: { freq: 660, dur: 0.12, gain: 0.25 },
    masterDefault: 0.6,
    startMuted: true,
  },
  hud: {
    // Plan 2c docked-card region the HUD keeps clear (viewport fracs, 1080p ref).
    reservedRect: { x: 0.0125, y: 0.022, w: 0.156, h: 0.322 },
  },
  brainPanel: {
    width: 300,
    cloudHeight: 150,
    cloudRotateHz: 0.017,
    breathHz: 0.14,
    breathAmp: 0.04,
    edgeOpacity: 0.15,
    firingThreshold: 0.32,
    hotRowThreshold: 0.5,
    escapeDecayS: 0.3,
    regionTintMix: 0.33,
    loadS: 1.2,
  },
  camera: {
    mouse: {
      minDistance: 1.5,
      maxDistance: 60,
      maxElevation: 1.45,
      rotateSpeed: 0.005,
      zoomSpeed: 0.0015,
      dragThreshold: 4,
    },
    OFFSET: { x: -3.2, y: 1.4, z: 0 },
    LOOKAHEAD: 2.5,
    omega: 14,
    IDLE_SWAY_HZ: 0.1,
    IDLE_SWAY_AMP: 0.02,
  },
  // The "Deep Field" aesthetic pass (Plan 02b) extends this block with motion +
  // post-FX dials (BREATH_*, BOB_*, ESCAPE_KICK, BLOOM_*, VIGNETTE, GRAIN,
  // EXPOSURE) and turns `grain` into a float. See
  // `docs/2026-09-09-visual-direction.md` §5–§6 and its §7 status table.
  aesthetic: {
    BASE_SIZE: 1.5,
    CORE_SIZE: 3.0,
    ACT_SWELL: 1.6,
    POINT_SCALE: 90,
    POINT_MAX: 14,
    // Depth shading: points past NEAR fade toward the background, reaching
    // FADE (0..1) of the way there by FAR — gives the cloud volume instead of a
    // flat stipple. Tuned to the brainScale-10 placement.
    POINT_DEPTH_NEAR: 8,
    POINT_DEPTH_FAR: 42,
    POINT_DEPTH_FADE: 0.45,
    FLAP_MIN: 8,
    FLAP_MAX: 34,
    FLAP_AMP: 0.9,
    theme: "dark",
    BOB_HZ: 0.5,
    BOB_AMP: 0.15,
    ESCAPE_KICK: { posShove: 0.6, rollDeg: 1.5, decayS: 0.3 },
    LOAD: { bannerS: 1.0, igniteS: 0.6, hudS: 0.8 },
    EXPOSURE: 1.0,
    // "bloom off" is STRENGTH: 0 (not null) so config.test.ts's finite/shape checks stay simple.
    BLOOM: {
      dark: { STRENGTH: 0.7, RADIUS: 0.4, THRESHOLD: 0.6 },
      light: { STRENGTH: 0, RADIUS: 0.4, THRESHOLD: 0.9 },
    },
    VIGNETTE: { dark: 0.2, light: 0.12 },
    GRAIN: { dark: 0.018, light: 0.015 },
  },
} as const;
